import json,pathlib,datetime,requests
p=pathlib.Path('workflow/batches/2026-10-08-remaining44');url='https://thewoksoflife.com/braised-pork-belly-dong-po-rou/'
ing=[('pork belly','2 pound slab (900g)'),('scallions','3 bunches, washed and cut in half lengthwise'),('ginger','8 slices'),('Shaoxing wine','2 cups'),('light soy sauce','2/3 cup'),('dark soy sauce','2 1/2 tablespoons'),('rock sugar','4–5 oz, depending on desired sweetness'),('water','for blanching; source gives no quantity')]
texts=["Wash the pork belly as a whole piece. Blanch it whole in boiling water for one minute and drain. This process gets rid of any impurities and also allows you to more easily cut the pork belly into same-size pieces. Cut the pork into 3 x 3 inch pieces. You can also make them 2 x 2 inches if you like them smaller. Set aside.","In a medium clay pot (preferably) or a medium (4-quart) regular pot, lay the scallions on the bottom in a thick, even layer. The scallions should cover the entire bottom of the pot. Space the ginger slices evenly over the scallions.","Next lay the pork belly skin-side down on top of the ginger and scallions. Pour over the Shaoxing wine, light soy sauce, and dark soy sauce. Add the rock sugar to the pot as well.","Now cover the pot and place it over medium high heat. Once the liquid in the pot comes to a boil, immediately turn down the heat to low and simmer for 90 minutes. No need to stir.","After 90 minutes, you have 2 choices: (1) Turn the pork belly skin-side up in the pot, cover, and let simmer for another 90 minutes. With the heat at the lowest setting, there should be plenty of liquid in the pot to cook the pork through the entire process—no need to add additional liquid. (2) Transfer the pork to a heat-proof plate, skin-side up (I used the small clay pots you see in the photos). Drizzle with some of the braising liquid, and place in a steamer for another 90 minutes.","Both methods should yield tender, delicious results! When serving, transfer the pork pieces to a plate. At this point, you can heat the braising liquid in a saucepan to reduce the sauce and drizzle it over the pork."]
steps=[{'order':i+1,'instruction':t,'duration':None,'heat':None} for i,t in enumerate(texts)]
tech=['Serves: 8','Prep: 20 mins','Cook: 3 hrs 30 mins','Total: 3 hrs 50 mins'];tips=['There is no need to stir while the pork is simmering; the scallions on the bottom of the pot prevent the meat from sticking.','Do not add water or stock to the braise.','Choose either simmering in the same pot or transferring to a steamer halfway through; these are alternatives, not consecutive stages.','Thicken any extra sauce by turning up the heat and reducing the liquid. Leftover sauce is good with rice or noodles.']
images=[]
for role,num,order,adj in [('hero',6,None,'Braised Pork Belly Dong Po Rou finished dish'),('step',1,2,texts[1]),('step',7,3,'Next, lay the pork belly skin-side down on top of the ginger and scallions.'),('step',8,3,'Pour over the Shaoxing wine, light soy sauce, and dark soy sauce. Add the rock sugar to the pot as well.'),('step',9,5,'Turn the pork belly skin-side up in the pot.'),('step',10,5,'Transfer the pork to a heat-proof plate, skin-side up; steam for another90minutes.'),('step',11,5,'Steaming alternative pictured'),('step',12,5,'Steaming alternative pictured')]:
 u=f'https://thewoksoflife.com/wp-content/uploads/2015/10/braised-pork-belly-{num}.jpg';r=requests.get(u,timeout=40);print(num,r.status_code,r.headers.get('content-type'))
 if r.status_code!=200 or not r.headers.get('content-type','').startswith('image/'):continue
 item={'role':role,'originalUrl':u,'repositoryPath':f'assets/dishes/sources/cn-019-woks-dongpo/{"hero" if role=="hero" else "step-"+str(order)+"-"+str(num)}.jpg','httpStatus':200,'contentType':r.headers['content-type'],'pageOrder':num,'adjacentText':adj}
 if order:item['stepOrder']=order
 images.append(item)
media=None
source={'sourceName':'The Woks of Life','sourceType':'website','url':url,'documentId':'pending-ingestion','retrievalMethod':'Normal web browser fetch, complete recipe card and instructional body; direct HTTP403 recorded without bypass','complete':True,'ingredients':[{'name':n,'amount':a,'raw':f'{a} {n}'} for n,a in ing],'steps':steps,'technique':tech,'tips':tips,'rawExcerpt':'Braised Pork Belly Dong Po Rou\nJudy\n'+'\n'.join(tech)+'\nIngredients\n'+'\n'.join(f'{a} {n}' for n,a in ing[:-1])+'\nInstructions\n'+'\n'.join(texts)+'\nNotes\n'+'\n'.join(tips),'selectionAssessment':{'qualifies':True,'ingredientCoverage':'complete','stepCoverage':'complete','internalCoherence':'coherent','heroImages':0,'mappedStepImages':0,'stepImageCoverage':0,'ingredientCount':len(ing),'executableStepCount':len(steps),'notes':['焯水用水来自步骤；原文未量化。杯和汤匙原样保留，未换算毫升。两种后90分钟工艺必须作为二选一。']}}
e={'recipeId':'cn-019','recipeName':'东坡肉','category':'chinese','createdAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'sources':[source],'sourceMode':'single_source','singleSourceReason':'读取数据库全部84份书籍文档并核对题名和正文，无东坡肉/东坡焖肉完整菜谱。豆果限定域检索未返回对应页面。Woks完整原料、方法和成品及过程图可用，单来源继续。','selectedSourceUrl':url,'selectionReason':'唯一可核验完整且自洽的整份信源，明确绍兴酒炖煮、不加水；有对应过程图。保留该版本所有配料用量及两种替代工艺，不混入其他来源。','ragEvidence':[],'notes':['源图URLs有对应操作语境，但当前直接HTTP403，未取得可下载照片；不得声称media验证通过。','Book search audit: cn-book-inventory.json contains all84actual database bookdocuments; no exactoralias Dongpo recipe.','原文炖煮分支合计180分钟，但来源Cook字段210分钟、Total230分钟；保留原始总时间并明确该差异，不以步骤相加重算。','原文未定义cup/tablespoon容量，不转换为ml。','Attempt: directWoksrequests403; normalwebfetchHTTPsuccess; no accesscontrols bypassed.','Attempt: Douguo name search returned no matching complete page.']}
(p/'cn-019.draft-evidence.json').write_text(json.dumps(e,ensure_ascii=False,indent=2),encoding='utf-8');(p/'cn-019.media-manifest.json').write_text(json.dumps({'recipeId':'cn-019','sourceUrl':url,'referer':url,'authorization':'user_confirmed_2026-09-16','items':images},ensure_ascii=False,indent=2),encoding='utf-8')
