import pathlib,json,datetime
p=pathlib.Path('workflow/batches/2026-10-08-remaining44');m=json.loads((p/'manifest.json').read_text(encoding='utf8'));configs={
'cn-012':('在两项启用网站限定检索未得到羊肉泡馍完整配方；豆果题名目录页不可访问，不能用羊汤或水盆羊肉替代。',[{'source':'豆果美食','url':'https://m.douguo.com/caipu/羊肉泡馍','result':'normalwebfetch inaccessible; no bypass'},{'source':'The Woks of Life','query':'yang rou pao mo site:thewoksoflife.com','result':'only lamb noodle soup /roujiamo near recipes, not exact dish'}]),
'cn-013':('可得豆果方中山胡辣汤仅一段方便料包做法；河南正宗胡辣汤候选是课程宣传，不含完整可执行工艺。无合格完整单一来源。',[{'source':'豆果美食','url':'https://www.douguo.com/cookbook/3300061.html','result':'HTTP200; 4listeditems,1paragraph method; incomplete/oilpack andseasonings omittedfromlist'},{'source':'豆果美食','url':'https://www.douguo.com/cookbook/2472236.html','result':'normalwebinaccessible; searchindexedcontentpromotespaidcourse, notfullmethod'},{'source':'The Woks of Life','query':'hu la tang site:thewoksoflife.com','result':'no exact complete recipe'}]),
'cn-018':('豆果金汤酸菜鱼页面正常抓取超时；索引显示调料包变体且原料表漏蒜、酸萝卜、老抽。Woks限定检索无酸菜鱼完整匹配；不拿水煮鱼替代。',[{'source':'豆果美食','url':'https://www.douguo.com/cookbook/3052707.html','result':'normalwebtimeout; no fulltext evidence accepted'},{'source':'The Woks of Life','query':'suan cai yu recipe site:thewoksoflife.com','result':'near matches squid/mustard greens and shuizhu fish, rejected dishidentity'}]),
'cn-022':('Woks完整候选为鸭胸煎制的简化Peking Duck，明显区别整鸭北京烤鸭工艺；未擅自改成煎鸭胸。豆果检索无可读取完整匹配。',[{'source':'The Woks of Life','url':'https://thewoksoflife.com/easy-peking-duck-mandarin-pancakes/','result':'normalwebsuccess fullcard/body; 4duckbreasts skilletseared; materiallydifferentvariant, rejected'},{'source':'豆果美食','query':'北京烤鸭的做法 豆果美食','result':'near names油烫鸭/芋泥香酥鸭 only; rejected'}]),
'cn-023':('Woks上海双菇鸡翅炖菜属于不同地区和配方变体；未用它替代东北小鸡炖蘑菇。豆果目录页不可读。',[{'source':'The Woks of Life','url':'https://thewoksoflife.com/chinese-braised-chicken-with-mushrooms/','result':'normalwebsuccess; ShanghaiJadeTempleinspired chickenwings/driedshiitake/woodear, notNortheasternhazelmushroomchicken, rejectedvariant'},{'source':'豆果美食','url':'https://m.douguo.com/caipu/小鸡炖蘑菇','result':'normalweb inaccessible'}]),
'cn-025':('启用来源检索无可核验西湖醋鱼完整配方；豆果目录不可访问，不以普通糖醋鱼替代。',[{'source':'豆果美食','url':'https://m.douguo.com/caipu/西湖醋鱼','result':'normalweb inaccessible'},{'source':'The Woks of Life','query':'west lake vinegar fish site:thewoksoflife.com','result':'no exact complete recipe'}]),
'cn-026':('唯一找到的豆果龙井虾仁候选抓取HTTP429/403；未绕过访问控制，不能把索引摘要冒充全文。Woks无对应完整菜谱。',[{'source':'豆果美食','url':'https://www.douguo.com/cookbook/1443891.html','result':'PythonHTTP429; normalweb403; no bypass'},{'source':'The Woks of Life','query':'shrimp longjing tea site:thewoksoflife.com','result':'no exact complete recipe'}]),
'cn-028':('豆果可读候选全部主料无用量，原料表漏料酒、生粉、油、鸡精、盐；其后正常网页抓取403。未认证为完整可执行信源。Woks近名虾菜不是清炒虾仁。',[{'source':'豆果美食','url':'https://www.douguo.com/cookbook/1336292.html','result':'initialPython200 extracted3unquantifiedmainitems/4steps; ingredientomissions; subsequentnormalweb403'},{'source':'The Woks of Life','query':'qing chao xia ren site:thewoksoflife.com','result':'near names/oil-friedwhole shrimp/Cashewshrimp only; rejected'}]),
'cn-037':('配置两项网站未获得佛跳墙完整配方；豆果目录不可读；不以菌菇汤等近名来源补齐。',[{'source':'豆果美食','url':'https://m.douguo.com/caipu/佛跳墙','result':'normalweb inaccessible'},{'source':'The Woks of Life','query':'buddha jumps wall site:thewoksoflife.com','result':'only cuisineoverview andmushroomnoodlesoup; no exact complete recipe'}]),
'cn-043':('豆果重庆小面候选页面抓取403；Woks结果为酸辣粉或上海面条，不匹配。',[{'source':'豆果美食','url':'https://www.douguo.com/cookbook/2490028.html','result':'normalweb403'},{'source':'The Woks of Life','query':'chongqing xiao mian site:thewoksoflife.com','result':'no exact complete recipe; suanlafen/stirfriedShanghai rejected'}]),
'cn-050':('Woks鸡蛋饼正文明确区分煎饼与鸡蛋饼；其链接JianBingApproximation用速冻葱油饼代替面糊并省略果子，属于不同变体；另一个链接只是游记无配方。豆果目录不可读。',[{'source':'豆果美食','url':'https://m.douguo.com/caipu/煎饼果子','result':'normalweb inaccessible'},{'source':'The Woks of Life','url':'https://thewoksoflife.com/chinese-breakfast-jidan-bing/','result':'normalwebsuccess; explicitlynotJianBing inbodylines75-80'},{'source':'The Woks of Life','url':'https://thewoksoflife.com/jian-bing-approximation/','result':'normalwebsuccess; frozen scallionpancake replacesbatter, nofriedfilling inrecipe; rejectmateriallydifferentapproximation'},{'source':'The Woks of Life','url':'https://thewoksoflife.com/the-jian-bing-experience/','result':'normalwebsuccess; travelstory noquantifiedrecipe'}])}
for r in m['recipes']:
 rid=r['recipeId']
 if rid not in configs:continue
 reason,attempts=configs[rid];out={'recipeId':rid,'recipeName':r['recipeName'],'category':'chinese','status':'failed','failedStage':'research','createdAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'reason':reason,'bookSearch':{'auditFile':'cn-book-inventory.json','scannedDocuments':84,'usableDocuments':79,'exactOrAcceptableAliasMatches':0,'excludedStatuses':['superseded','rejected','invalid'],'assessment':'No complete same-dish recipe in current database books; no book supplementation fabricated.'},'attemptedSources':attempts,'evidencePackage':None,'ingestion':{'performed':False,'reason':'No qualifying complete exactdishsource; do not ingest partial snippets or unrelated variants as this entity.'}}
 (p/f'{rid}.research-failure.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf8')
print('Recorded11recipelevelresearchfailures')
f=p/'cn-book-inventory.json';x=json.loads(f.read_text(encoding='utf8'));x['scannedCount']=84;x['usableCount']=79;x['excludedCount']=5;f.write_text(json.dumps(x,ensure_ascii=False,indent=2),encoding='utf8')
