import json,pathlib,datetime
b=pathlib.Path('workflow/batches/2026-10-08-remaining44');p=b/'final-database-verification.json';j=json.loads(p.read_text(encoding='utf-8'));missing=[]
for r in j['recipes']:
 for c in r['retrieval']['candidates']:
  if not c['semanticCount'] or not c['hybridCount']:missing.append({'recipeId':r['recipeId'],**c})
j['allCurrentCandidatesNormallyRetrievable']=not missing;j['candidateRetrievalMissing']=missing
if missing:j['errors'].append('Some current candidates missing from normal semantic/hybrid results');j['ok']=False
j['west024IndependentMediaAudit']['independentLocalFileVerification']=json.loads((b/'west-024.final-local-media-verification.json').read_text(encoding='utf-8'))
unknown=[d for d in j['documents'] if d['sourceAuthor'] is None];j['authorAttributionSummary']={'sourceAuthorKnownDocumentCount':len(j['documents'])-len(unknown),'sourceAuthorNullDocumentCount':len(unknown),'sourceAuthorNullDocumentIds':[d['documentId'] for d in unknown],'documentsWithIndependentlyVerifiedMediaAttribution':sum(bool(d['mediaChecks']) for d in j['documents']),'distinction':'source.author belongs to original hashed content identity. Null means not stored in that field, not an invented author. Independently traced original bylines/images are carried in verified mediaReferences where available; this audit makes no source.author rewrite and does not equate separate media attribution with populated source.author.'}
j['notes'].append('CN044 media review correction was reported concurrently near the end of verification. Media comparisons describe the initial readback snapshot against then-current frozen evidence; any subsequent media correction must retain its separate parent-owned provenance audit. This audit never mutated DB metadata.')
j['embeddingVerification']={'model':'voyage-4','modelBasis':'Existing per-source ingestion audits; no content re-embedding performed','dimensionBasis':'Actual readback embedding lengths, only aggregated dimensions retained; no vector values in artifact','currentDimensionCounts':j['counts']['embeddingDimensionCounts']}
j['finalizedAt']=datetime.datetime.now(datetime.timezone.utc).isoformat();p.write_text(json.dumps(j,ensure_ascii=False,indent=2),encoding='utf-8');print(json.dumps({'ok':j['ok'],'recipes':len(j['recipes']),'candidateRetrievalMissing':missing,'knownAuthors':len(j['documents'])-len(unknown),'unknownAuthors':len(unknown),'mediaAttributionDocuments':j['authorAttributionSummary']['documentsWithIndependentlyVerifiedMediaAttribution'],'counts':j['counts']},ensure_ascii=False))
