import { readFile, writeFile, stat } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { createRecipeCatalog, splitRecipeIngredients, splitRecipeSteps } from '../../../tools/workflow/recipe-state.mjs';
import { validateRecipeChange } from '../../../tools/workflow/validate-recipe.mjs';
const dir = new URL('./', import.meta.url);
const before = JSON.parse(await readFile(new URL('before.json', dir), 'utf8'));
const manifest = JSON.parse(await readFile(new URL('manifest.json', dir), 'utf8'));
const catalog = createRecipeCatalog();
const targetId = process.argv[2];
const current = catalog.find(r => r.id === targetId);
if (!current) throw new Error('Unknown target');
const isolated = structuredClone(before);
for (const r of isolated.recipes) if (r.id !== targetId) Object.assign(r, catalog.find(c => c.id === r.id));
const result = validateRecipeChange({beforeSnapshot: isolated, currentCatalog: catalog, targetId, requireChange: true, allowedStableFieldChanges: ['source']});
const evidenceRaw = await readFile(new URL(`${targetId}.evidence.json`, dir), 'utf8');
const evidence = JSON.parse(evidenceRaw);
const check = (name, passed) => { result.checks.push({name, passed}); if (!passed) result.errors.push(name); };
const original = current.record.howtocook;
const source = evidence.sources[0];
check('selected_pinned_source', current.record.source === source.url && current.record.source.includes(manifest.commit));
check('exact_complete_upstream_markdown', original?.rawMarkdown === source.rawExcerpt);
check('upstream_content_sha256', original?.sha256 === createHash('sha256').update(original?.rawMarkdown || '').digest('hex'));
check('ingested_source_document', Boolean(source.documentId && evidence.ragEvidence.some(c => c.documentId === source.documentId)));
const ingredientRows = splitRecipeIngredients(current.record.ingredients);
const steps = splitRecipeSteps(current.record.steps).map(s => s.replace(/^\d+[）)]\s*/, ''));
const balanced = (s, a, b) => {let n=0; for(const c of s){if(c===a)n++;if(c===b)n--;if(n<0)return false;}return n===0;};
check('ingredient_brackets_and_rows', ingredientRows.every(s => balanced(s,'（','）') && balanced(s,'(',')') && !/^(另取|另备|可选作|用于装饰)/.test(s)));
check('step_brackets', steps.every(s => balanced(s,'（','）') && balanced(s,'(',')')));
for(const image of original?.images || []) {
  check(`local_image_${image.path}`, /^assets\/dishes\/howtocook\//.test(image.path) && !image.path.includes('..') && (await stat(image.path)).size > 0);
}
const allowed = new Set(manifest.recipes.filter(r => r.status === 'matched').map(r => r.recipeId));
check('batch_scope_only', before.recipes.every(r => allowed.has(r.id) || JSON.stringify(r) === JSON.stringify(catalog.find(c => c.id === r.id))));
const generatedText = await readFile(new URL('../../../data/recipes.js', import.meta.url), 'utf8');
const generated = JSON.parse(generatedText.slice(generatedText.indexOf('=') + 1).trim().replace(/;$/, '')).find(r => r.id === targetId);
check('generated_original_preserved', generated?.howtocook?.rawMarkdown === original?.rawMarkdown);
check('generated_steps_match_canonical', JSON.stringify(generated.steps.map(s => s.instruction)) === JSON.stringify(steps));
check('generated_ingredient_labels_match', JSON.stringify(generated.ingredients.map(s => s.label)) === JSON.stringify(ingredientRows));
check('unknown_time_not_invented', current.record.timing ? generated.time === current.record.timing.totalMinutes : generated.time === null);
check('unknown_yield_not_invented', current.record.servings != null ? generated.defaultServings === current.record.servings : generated.defaultServings === null);
result.ok = !result.errors.length;
result.evidencePackageHash = createHash('sha256').update(evidenceRaw.replace(/\r\n/g,'\n')).digest('hex');
await writeFile(new URL(`${targetId}.target.json`,dir), JSON.stringify({recipeId:targetId,record:current.record,generated,renderedIngredientRows:ingredientRows,renderedSteps:steps},null,2));
await writeFile(new URL(`${targetId}.validation.json`,dir), JSON.stringify(result,null,2));
console.log(JSON.stringify({targetId,ok:result.ok,errors:result.errors}));
if(!result.ok)process.exitCode=1;
